owner: zn3x
repo: ehr_status

sites:
  - name: Eternal Harmony radio
    url: https://eternalharmonyradio.com/

status-website:
  cname: status.eternalharmonyradio.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Eternal Harmony Radio
  introTitle: "Status page"
  introMessage: Monitor downtimes using this status page
  navbar:
    - title: Eternal harmony radio
      href: https://eternalharmonyradio.com
    - title: Status page source code
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
