owner: zn3x
repo: ehr_status

sites:
  - name: WEB
    url: https://eternalharmonyradio.com/
  - name: API
    url: https://eternalharmonyradio.com/api/v1/status
    expectedStatusCodes:
      - 401
  - name: Broadcast server
    url: https://eternalharmonyradio.com/radio/invalid_stream.mp3
    expectedStatusCodes:
      - 404

status-website:
  cname: status.eternalharmonyradio.com
  logoUrl: https://eternalharmonyradio.com/logo-fa904ad8a40cb4dd.png
  name: Eternal Harmony Radio
  introTitle: "Status page"
  introMessage: Monitor downtimes using this status page
  navbar:
    - title: Radio
      href: https://eternalharmonyradio.com
    - title: Status page source code
      href: https://github.com/$OWNER/$REPO
  themeUrl: https://status.eternalharmonyradio.com/theme.css
